name: string_typography
description: A string converter that converts strings to widgets typography.
version: 0.0.1-dev.2
issue_tracker: https://github.com/nggepe/string_typography
homepage: "https://github.com/nggepe/string_typography"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mocktail_image_network: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  coverage: ^1.0.1
  mocktail: ^0.1.0
  pedantic: ^1.10.0
  rxdart: ^0.26.0
  test: ^1.16.0

flutter:
